name: 🔧 Hardware Design Check

on:
  pull_request:
    paths:
      - '**/*.kicad_*'
      - '**/*.sch'
      - '**/*.brd'
      - '**/*.lib'
      - '**/gerber/**'
      - '**/hardware/**'
      - '**/design/**'
  push:
    branches: [ main, develop ]
    paths:
      - '**/*.kicad_*'
      - '**/*.sch'
      - '**/*.brd'
      - '**/*.lib'
      - '**/gerber/**'
      - '**/hardware/**'
      - '**/design/**'

jobs:
  hardware-check:
    name: 🔍 Hardware Files Validation
    runs-on: ubuntu-latest
    
    steps:
    - name: 📥 Checkout code
      uses: actions/checkout@v4
      
    - name: 🔍 Check for hardware files
      run: |
        echo "🔍 Checking for hardware design files..."
        
        # Check for KiCad files
        if find . -name "*.kicad_pro" -o -name "*.kicad_pcb" -o -name "*.kicad_sch" | grep -q .; then
          echo "✅ KiCad project files found"
          KICAD_FILES=true
        else
          echo "ℹ️ No KiCad files found"
          KICAD_FILES=false
        fi
        
        # Check for other EDA files
        if find . -name "*.sch" -o -name "*.brd" -o -name "*.lib" | grep -q .; then
          echo "✅ EDA design files found"
          EDA_FILES=true
        else
          echo "ℹ️ No EDA files found"
          EDA_FILES=false
        fi
        
        # Store results for next steps
        echo "KICAD_FILES=$KICAD_FILES" >> $GITHUB_ENV
        echo "EDA_FILES=$EDA_FILES" >> $GITHUB_ENV

    - name: 📋 Validate project structure
      run: |
        echo "🔍 Validating hardware project structure..."
        
        # Check for required directories in hardware projects
        REQUIRED_DIRS=("components" "design" "documentation" "firmware")
        MISSING_DIRS=()
        
        for dir in "${REQUIRED_DIRS[@]}"; do
          if [ ! -d "$dir" ]; then
            MISSING_DIRS+=("$dir")
            echo "⚠️ Missing directory: $dir"
          else
            echo "✅ Found directory: $dir"
          fi
        done
        
        if [ ${#MISSING_DIRS[@]} -gt 0 ]; then
          echo "::warning::Missing required directories: ${MISSING_DIRS[*]}"
          echo "::warning::For hardware projects, consider using the template structure"
        fi

    - name: 📄 Check for documentation
      run: |
        echo "🔍 Checking documentation completeness..."
        
        # Check for README files
        if [ -f "README.md" ]; then
          echo "✅ Main README.md found"
          
          # Check README content for hardware projects
          if grep -q -i "hardware\|circuit\|pcb\|schematic" README.md; then
            echo "✅ README mentions hardware content"
          else
            echo "ℹ️ README doesn't mention hardware-specific content"
          fi
        else
          echo "❌ Main README.md not found"
          echo "::error::README.md is required for all projects"
          exit 1
        fi
        
        # Check for component documentation
        if [ -d "components" ]; then
          if [ -f "components/README.md" ]; then
            echo "✅ Components documentation found"
          else
            echo "⚠️ components/README.md recommended"
            echo "::warning::Consider adding components/README.md for better documentation"
          fi
        fi
        
        # Check for design documentation
        if [ -d "design" ]; then
          if [ -f "design/README.md" ]; then
            echo "✅ Design documentation found"
          else
            echo "⚠️ design/README.md recommended"
          fi
        fi

    - name: 🗂️ Validate file organization
      run: |
        echo "🔍 Checking file organization..."
        
        # Check for Gerber files in correct location
        if find . -name "*.gbr" -o -name "*.gbl" -o -name "*.gtl" | grep -q .; then
          echo "✅ Gerber files found"
          
          if find design/pcb -name "*.gbr" -o -name "*.gbl" -o -name "*.gtl" 2>/dev/null | grep -q .; then
            echo "✅ Gerber files in design/pcb/ directory"
          else
            echo "⚠️ Gerber files not in standard design/pcb/ location"
            echo "::warning::Consider organizing Gerber files in design/pcb/gerber/"
          fi
        fi
        
        # Check for datasheets
        if find . -name "*.pdf" | grep -i datasheet | grep -q .; then
          echo "✅ Datasheet files found"
          
          if find components/datasheets -name "*.pdf" 2>/dev/null | grep -q .; then
            echo "✅ Datasheets organized in components/datasheets/"
          else
            echo "⚠️ Datasheets not in standard components/datasheets/ location"
          fi
        fi

    - name: 🔍 Check for common issues
      run: |
        echo "🔍 Checking for common hardware project issues..."
        
        # Check for large binary files
        echo "Checking for large files..."
        find . -type f -size +10M -not -path "./.git/*" | while read file; do
          echo "⚠️ Large file detected: $file ($(du -h "$file" | cut -f1))"
          echo "::warning::Large file detected: $file - consider using Git LFS"
        done
        
        # Check for backup files
        if find . -name "*-bak" -o -name "*.bak" -o -name "*~" | grep -q .; then
          echo "⚠️ Backup files found - these should not be committed"
          find . -name "*-bak" -o -name "*.bak" -o -name "*~" | head -5
          echo "::warning::Backup files detected - consider adding to .gitignore"
        fi
        
        # Check for temporary files
        if find . -name "*.tmp" -o -name "*.temp" | grep -q .; then
          echo "⚠️ Temporary files found"
          echo "::warning::Temporary files detected - consider adding to .gitignore"
        fi

    - name: 📊 Generate hardware project summary
      run: |
        echo "📊 Hardware Project Summary" > hardware-summary.md
        echo "=========================" >> hardware-summary.md
        echo "" >> hardware-summary.md
        
        # Count different file types
        echo "### File Types Found:" >> hardware-summary.md
        
        KICAD_COUNT=$(find . -name "*.kicad_*" | wc -l)
        SCH_COUNT=$(find . -name "*.sch" | wc -l)
        PCB_COUNT=$(find . -name "*.kicad_pcb" -o -name "*.brd" | wc -l)
        GERBER_COUNT=$(find . -name "*.gbr" -o -name "*.gbl" -o -name "*.gtl" | wc -l)
        PDF_COUNT=$(find . -name "*.pdf" | wc -l)
        
        echo "- KiCad files: $KICAD_COUNT" >> hardware-summary.md
        echo "- Schematic files: $SCH_COUNT" >> hardware-summary.md
        echo "- PCB files: $PCB_COUNT" >> hardware-summary.md
        echo "- Gerber files: $GERBER_COUNT" >> hardware-summary.md
        echo "- PDF documents: $PDF_COUNT" >> hardware-summary.md
        echo "" >> hardware-summary.md
        
        # Check structure compliance
        echo "### Template Compliance:" >> hardware-summary.md
        for dir in components design documentation firmware; do
          if [ -d "$dir" ]; then
            echo "- ✅ $dir/" >> hardware-summary.md
          else
            echo "- ❌ $dir/" >> hardware-summary.md
          fi
        done
        
        echo "" >> hardware-summary.md
        echo "Generated on: $(date)" >> hardware-summary.md
        
        # Output summary
        cat hardware-summary.md
        
        # Save as artifact
        echo "::notice::Hardware project validation completed"

    - name: 📎 Upload summary
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: hardware-validation-summary
        path: hardware-summary.md
        retention-days: 30

  bill-of-materials:
    name: 📋 BOM Validation
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[BOM]') || github.event_name == 'pull_request'
    
    steps:
    - name: 📥 Checkout code
      uses: actions/checkout@v4
      
    - name: 🔍 Check for BOM files
      run: |
        echo "🔍 Looking for Bill of Materials files..."
        
        # Look for BOM files
        BOM_FILES=$(find . -name "*bom*" -o -name "*BOM*" | grep -E "\.(csv|xlsx?|pdf)$" || true)
        
        if [ -n "$BOM_FILES" ]; then
          echo "✅ BOM files found:"
          echo "$BOM_FILES"
          
          # Check if in standard location
          if find design/pcb -name "*bom*" -o -name "*BOM*" 2>/dev/null | grep -q .; then
            echo "✅ BOM files in design/pcb/ directory"
          else
            echo "::warning::BOM files not in standard design/pcb/ location"
          fi
        else
          echo "⚠️ No BOM files found"
          echo "::warning::Consider adding Bill of Materials for hardware projects"
        fi

    - name: 📊 BOM Analysis
      run: |
        echo "📊 Analyzing BOM content..."
        
        # Look for CSV BOMs specifically for automated analysis
        CSV_BOMS=$(find . -name "*bom*.csv" -o -name "*BOM*.csv" || true)
        
        if [ -n "$CSV_BOMS" ]; then
          echo "CSV BOM files found for analysis:"
          for bom in $CSV_BOMS; do
            echo "Analyzing: $bom"
            
            # Count components
            COMPONENT_COUNT=$(tail -n +2 "$bom" | wc -l)
            echo "  - Components: $COMPONENT_COUNT"
            
            # Check for required columns (common BOM format)
            if head -1 "$bom" | grep -q -i "reference\|designator"; then
              echo "  - ✅ Reference designators found"
            fi
            
            if head -1 "$bom" | grep -q -i "value"; then
              echo "  - ✅ Component values found"
            fi
            
            if head -1 "$bom" | grep -q -i "footprint\|package"; then
              echo "  - ✅ Footprint information found"
            fi
            
            if head -1 "$bom" | grep -q -i "manufacturer\|mfr"; then
              echo "  - ✅ Manufacturer information found"
            fi
          done
        else
          echo "ℹ️ No CSV BOM files found for automated analysis"
        fi
